Lesson 10
IvanKOS7/rails-basic pull request #13
Opened 2022-02-19 15:41 UTC by IvanKOS7

2022-02-19 18:02 UTC, BubuntuClu requested changes

2022-02-19 18:02 UTC, BubuntuClu commented on app/models/user.rb
> +  EMAIL_REGEXP = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i.freeze
используй `URI` модуль, чтобы найти регулярку для почты

2022-02-19 18:02 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, format: { with: EMAIL_REGEXP }
Проверяйте формат и **уникальность** атрибута email для пользователя

2022-02-19 18:02 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
дублирует путь на 7ой строке

2022-02-19 18:02 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
дублирует путь на 6ой строке

2022-02-23 17:42 UTC, BubuntuClu requested changes

2022-02-23 17:42 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  # def referer
не нужный код удаляй, не надо его тащить за собой

2022-02-23 17:42 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +       redirect_to login_path
не сохраняешь путь, куда сделать редирект

2022-02-23 17:42 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +  def set_cookie_last_path
тут уже поздно сохранять

2022-02-23 17:42 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:last_path]
`redirect_to cookies[:last_path] || root_path`

2022-02-23 17:42 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +     #когда запускаем тест пасажнужно менять @test_passage.user = current_user.id
тут что-то надо сделать с этим?

2022-02-23 17:42 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +      autheticate_user!
с какой целью вызываешь этот метод?

2022-02-23 17:42 UTC, BubuntuClu commented on app/views/sessions/_form.html.erb
> +<% if flash[:alert] %>
это надо заменить на хэлпер для флешек

2022-02-23 17:42 UTC, BubuntuClu commented on config/routes.rb
> +  resources :sessions, except: :index
в контроллере у тебя многих методов нет. может тут напутал что-то?

2022-02-23 17:42 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, format: { with:  URI::MailTo::EMAIL_REGEXP }, uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2022-02-24 17:23 UTC, BubuntuClu requested changes

2022-02-24 17:23 UTC, BubuntuClu commented on db/migrate/20220117153023_add_user_email_column.rb
> +    add_index :users, :email, unique: true
https://github.com/IvanKOS7/rails-basic/pull/12#discussion_r805189002
https://github.com/IvanKOS7/rails-basic/pull/7#discussion_r785099730

давай для закрепления информации еще раз почитаешь эти комментарии

2022-02-24 18:11 UTC, IvanKOS7 commented on db/schema.rb
>    enable_extension "plpgsql"
t.index ["email"], name: "index_users_on_email", unique: true
я проверил

2022-02-25 14:40 UTC, merged