Add lesson-6
IvanKOS7/rails-basic pull request #7
Opened 2022-01-14 12:41 UTC by IvanKOS7

2022-01-14 19:27 UTC, BubuntuClu requested changes

2022-01-14 19:27 UTC, BubuntuClu commented on test-guru/app/models/question.rb
> +    def right_answers_count
валидации в модели вызываются при изменении/сохрании объекта этого класса. при добавлении вопроса, объект вопроса никак не изменяется. валидация должна быть в другой модели

2022-01-14 19:27 UTC, BubuntuClu commented on test-guru/app/models/question.rb
> +  validate :right_answers_count
когда перенесешь, добавь опцию чтобы валидация вызывалсь только при создании объекта

2022-01-14 19:27 UTC, BubuntuClu commented on test-guru/app/models/question.rb
> +       errors.add(:answers) if self.answers.count >= 4 || < 1
убери ограничения по минимальному количеству вопросов

2022-01-14 19:27 UTC, BubuntuClu commented on test-guru/app/models/test.rb
> +  belongs_to :category, optional: true
это не опциональная ассоциация, а обязательная, убери опцию

2022-01-14 19:27 UTC, BubuntuClu commented on test-guru/app/models/test.rb
> +  validates :title, presence: true, uniqueness: true
униклаьность должна быть на пару полей, а не на каждое поле отдельно

2022-01-14 19:27 UTC, BubuntuClu commented on test-guru/app/models/test.rb
> +  scope :sort_test, -> (category_name) { order(title: :desc).joins(:category).where("categories.title like ? ", category_name).pluck(:title) }
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2022-01-14 19:27 UTC, BubuntuClu commented on test-guru/app/models/user.rb
> +  scope :find_user_tests_by_level, -> (level) { Test.where("tests.level = ?", level) }
этот скоуп не равноценен методу. так что смысла в скоупе нет

2022-01-14 19:27 UTC, BubuntuClu commented on test-guru/db/migrate/20211210113923_create_users.rb
> +      t.string :email
нельзя менять миграции которые уже смержены. верни код, который тут был и вноси правки через новую миграцию

2022-01-14 19:27 UTC, BubuntuClu commented on test-guru/app/models/test.rb
> +  validates :title, presence: true, uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2022-01-17 18:47 UTC, BubuntuClu requested changes

2022-01-17 18:47 UTC, BubuntuClu commented on test-guru/app/models/answer.rb
> +        errors.add(:answer, "The number of answers cannot be more than 4. Answers full.") if Answer.where("question_id= ?", self.question_id).count >= 4
`Answer.where("question_id= ?", self.question_id)` - а что насчет ассоциации question? используй ее тут вместо этого запроса

2022-01-17 18:47 UTC, BubuntuClu commented on test-guru/db/migrate/20220117180515_add_test_title_uniq_index.rb
> +      t.index :title, unique: true
индекс должен быть составным(на две колонки). сейчас у тебя в БД проверяется униклаьность только по одному названию, а должен по названию и уровню

2022-01-17 18:47 UTC, BubuntuClu commented on test-guru/app/models/test.rb
> +  validates :title, presence: true, uniqueness: true
`униклаьность должна быть на пару полей, а не на каждое поле отдельно` - это все еще надо поправить. сейчас в модели проверяется уникальность только названия, а не названия+уровень. это должно быть составное поле для проверки

2022-01-17 18:47 UTC, BubuntuClu commented on test-guru/app/models/test.rb
> +    Test.order(title: :desc).all_test_with_category.where("categories.title like ? ", category_name).pluck(:title)
часть этого метода надо заменить на скоуп, как ты и делал. а сортировку и выборку надо оставить в методи и применить их к рузальтату скоупа

2022-01-17 18:47 UTC, BubuntuClu commented on test-guru/db/schema.rb
> -  create_table "user_tests", id: false, force: :cascade do |t|
почему удалилась эта таблица? что случилось?

2022-01-17 20:08 UTC, IvanKOS7 commented on test-guru/db/schema.rb
> -  create_table "user_tests", id: false, force: :cascade do |t|
Здесь все норм. Я в каком-то из заданий создавал вручную, удалил из бд и забыл про схему

2022-01-18 17:15 UTC, BubuntuClu approved these changes

2022-01-18 17:15 UTC, BubuntuClu commented on test-guru/app/models/test.rb
> +  validates :title, :level, uniqueness: true
` validates :title, presence: true, uniqueness: { scope: :level }`

то как у тебя написано, будет проверять два поля в отдельности

2022-01-20 11:57 UTC, merged