Add lesson-8
IvanKOS7/rails-basic pull request #9
Opened 2022-02-06 08:05 UTC by IvanKOS7

Question, and Test views created. 
Added basic navigation

2022-02-06 17:20 UTC, BubuntuClu requested changes

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/controllers/questions_controller.rb
> +    @test = Test.find(@question.test_id)
1 - зачем нужен тест, чтобы редактировать вопрос?
2 - если вдруг и зачем-то надо, то у тебя же есть ` before_action :find_test`

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/controllers/questions_controller.rb
> +     params.require(:question).permit(:body, :test_id)
не нужно сюда добавлять параметр теста, ты его подставляешь из ассоциации

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/helpers/questions_helper.rb
> +  def question_header(action)
передавай в метод объект вопроса и по состоянию вопроса определяй какой заголовок вывести используя метод `new_record?/persisted?`

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/views/layouts/_footer.html.erb
> +    RoR educational project-<a href="https://github.com/IvanKOS7/rails-basic/tree/main/test-guru">Test Guru </a>
ссылки на сторонние ресурсы открываем в новой вкладке

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/views/layouts/_footer.html.erb
> +    by <a href="https://github.com/IvanKOS7">Ivan K</a>
и тут

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/views/questions/index.html.erb
> +<h1>Test questions</h1>
этого метода и вьюхи уже не должно быть. все отображение переходит в `tests#show`

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/views/questions/edit.html.erb
> +<%= question_header(:edit) %>
дублирование кода из `_form` файла. по сути в файле `edit/new` будет только вызов отрисовки `form

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/views/questions/_form.html.erb
> +<%= render 'shared/errors', resource: @question %>
соблюдай вложенность кода во вью файлах, чтобы разметку было легко читать

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/views/tests/edit.html.erb
> +<%= link_to 'Back', tests_path %>
эту строку тоже можно в `form` разместить

2022-02-06 17:20 UTC, BubuntuClu commented on test-guru/app/views/tests/index.html.erb
> +    <th colspan="3">Actions</th>
обычно действия с объектми размещают в самом конце списка, чтобы ты уже имел полное представление об объекте на тот момент когда добрался до действий

2022-02-07 11:26 UTC, IvanKOS7 commented on test-guru/app/controllers/questions_controller.rb
> +    @test = Test.find(@question.test_id)
Это чтобы хедер работал, когда вызывается edit - там нет в парамсах test_id

2022-02-09 11:45 UTC, merged